const disposableDomains = [
    '10minutemail.com', 'guerrillamail.com', 'mailinator.com', 'temp-mail.org',
    'throwaway.email', 'yopmail.com', 'maildrop.cc', 'tempail.com', 'mv6a.com',
    'temp-mail.io', 'dispostable.com', '0-mail.com', 'mail-temporaire.fr',
    'spamgourmet.com', 'jetable.org', 'mailcatch.com', 'fakeinbox.com',
    'mailnull.com', 'spam4.me', 'incognitomail.org', 'mailmetrash.com',
    'binkmail.com', 'safetymail.info', 'suremail.info', 'grr.la',
    'guerrillamail.biz', 'guerrillamail.de', 'sharklasers.com', 'pokemail.net',
    'spamgourmet.net', 'spamgourmet.org', 'meltmail.com', 'fixmail.tk',
    '10mail.org', '20minutemail.com', '2prong.com', '33mail.com',
    'anonbox.net', 'deadaddress.com', 'dontsendmespam.de', 'drdrb.net',
    'e4ward.com', 'emailto.de', 'fixmail.tk', 'gishpuppy.com', 'guerrillamail.net',
    'haltospam.com', 'incognitomail.org', 'kasmail.com', 'klzlk.com',
    'kurzepost.de', 'lifebyfood.com', 'lovemeleaveme.com', 'mailin8r.com',
    'mailinator.net', 'mailinator2.com', 'mytemp.email', 'nobulk.com',
    'noclickemail.com', 'nogmailspam.info', 'nomail.xl.cx', 'nospamfor.us',
    'objectmail.com', 'obobbo.com', 'oopi.org', 'opayq.com', 'owlpic.com',
    'pookmail.com', 'proxymail.eu', 'rcpt.at', 'reallymymail.com',
    'safe-mail.net', 'saynotospams.com', 'selfdestructingmail.com',
    'sendspamhere.com', 'spamcero.com', 'spamcon.org', 'spamcorptastic.com',
    'spamcowboy.com', 'spamcowboy.net', 'spamcowboy.org', 'spamday.com',
    'spamex.com', 'spamfree24.org', 'spamhole.com', 'spamify.com',
    'spaminator.de', 'spamkill.info', 'spaml.com', 'spaml.de', 'spammotel.com',
    'spamobox.com', 'spamslicer.com', 'speed.1s.fr', 'suremail.info',
    'temp.emerald.ne.jp', 'tempail.com', 'tempemail.biz', 'tempemail.com',
    'tempmail.it', 'tempymail.com', 'thankyou2010.com', 'thisisnotmyrealemail.com',
    'throam.com', 'tilien.com', 'tmailinator.com', 'tradermail.info',
    'trash2009.com', 'trashemail.de', 'trashmail.at', 'trashmail.com',
    'trashmail.de', 'trashmail.me', 'trashmail.net', 'trashmail.org',
    'trashmail.ws', 'trashymail.com', 'tyldd.com', 'upliftnow.com',
    'uplipht.com', 'venompen.com', 'veryrealemail.com', 'walkmail.net',
    'wetrainbayarea.com', 'wetrainbayarea.org', 'wh4f.org', 'whyspam.me',
    'willselfdestruct.com', 'xoxy.net', 'yogamaven.com', 'yuurok.com',
    'zehnminutenmail.de', 'zetmail.com', 'zippymail.info', 'zoemail.org',
    'aiwanlab.com',
    'fintehs.com'
];

export default disposableDomains;
